# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hotUpdateTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for hotUpdateTest
  platform :ios, '7.0'
  pod 'AFNetworking', '3.1.0'

end
